BANKROLL = 1000.0

MAX_TOTAL_PICKS = 12
MAX_PICKS_PER_MATCH = 2
MAX_PICKS_PER_LEAGUE = 3

ALLOW_RISK_IN_DASHBOARD = True

SAFE_MIN_EDGE = 0.07
LOW_MIN_EDGE = 0.02

SAFE_MIN_ODDS = 1.20
SAFE_MAX_ODDS = 3.50
LOW_MAX_ODDS = 5.00

MIN_BOOKS_FOR_SAFE = 2
MIN_BOOKS_FOR_LOW = 2